categories:
- Computational chemistry
- Molecular Dynamics
description: Generate phonons (pm-asephonons)
homepage_url: https://github.com/muon-spectroscopy-computational-project/muon-galaxy-tools
long_description: |
  Given an input structure, generates a set of phonon configurations.
name: pm_asephonons
owner: muon-spectroscopy-computational-project
remote_repository_url: https://github.com/muon-spectroscopy-computational-project/muon-galaxy-tools/main/pm_asephonons
