categories:
- Computational chemistry
- Molecular Dynamics
description: Optimise muonated structures (pm-uep-opt)
homepage_url: https://github.com/muon-spectroscopy-computational-project/muon-galaxy-tools
long_description: |
  Given input muonated structures, optimise them with uep.
name: pm_uep_opt_write
owner: muon-spectroscopy-computational-project
remote_repository_url: https://github.com/muon-spectroscopy-computational-project/muon-galaxy-tools/main/pm_uep_opt_write
