categories:
- Computational chemistry
- Molecular Dynamics
description: Cluster optimised structures (pm-muairss-read)
homepage_url: https://github.com/muon-spectroscopy-computational-project/muon-galaxy-tools
long_description: |
  Given an input set of optimised muonated structures (UEP, CASTEP or DFTB+), performs clustering
name: pm_muairss_read
owner: muon-spectroscopy-computational-project
remote_repository_url: https://github.com/muon-spectroscopy-computational-project/muon-galaxy-tools/main/pm_muairss_read
