categories:
- Computational chemistry
- Molecular Dynamics
description: Generate muon structures (pm-muairss)
homepage_url: https://github.com/muon-spectroscopy-computational-project/muon-galaxy-tools
long_description: |
  TODO
name: pm_muairss_write
owner: elichad
remote_repository_url: https://github.com/muon-spectroscopy-computational-project/muon-galaxy-tools/main/pm_muairss_write
